services:
  redis:
    image: redis
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"

  ratelimiter-app:
    build: .
    container_name: ratelimiter-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379