services:
  redis:
    image: redis
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"

  ratelimiter-app:
    build: .
    container_name: ratelimiter-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  prometheus:
    image: prom/prometheus
    container_name: ratelimiter-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - ratelimiter-app

  grafana:
    image: grafana/grafana
    container_name: ratelimiter-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus