spring.application.name=ratelimiter
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8080

ratelimiter.windowSeconds=60
ratelimiter.limits.data=5
ratelimiter.limits.login=10
ratelimiter.limits.admin=2
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,prometheus}
management.endpoint.prometheus.enabled=${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED:true}